import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
     <div>
      <h1>Dashboard for social media </h1>
      <ul>
        <li>Instagram</li>
        <li>Twitter</li>
        <li>Linkedin</li>
        <li>Youtube</li>
      </ul>
     </div>
    </div>
  )
}
